"""Render an invoice to a PDF document (reportlab)."""
from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BRAND = colors.HexColor("#12314f")
ACCENT = colors.HexColor("#2f7fd1")
LIGHT = colors.HexColor("#f1f5f9")


def _money(n: float) -> str:
    return f"${n:,.2f}"


def render_invoice_pdf(*, org, invoice, work_order, customer, equipment) -> bytes:
    """Return PDF bytes for an invoice. Arguments are ORM objects (or duck-typed)."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter, topMargin=0.7 * inch, bottomMargin=0.7 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch, title=f"Invoice {invoice.number}",
    )
    styles = getSampleStyleSheet()
    h = styles["Heading1"]; h.textColor = BRAND
    normal = styles["Normal"]
    small = styles["Normal"].clone("small"); small.fontSize = 8; small.textColor = colors.HexColor("#64748b")
    right = normal.clone("right"); right.alignment = 2
    story = []

    # Header: company + INVOICE title
    header = Table(
        [[
            Paragraph(f"<b>{org.name}</b><br/><font size=8 color='#64748b'>Industrial Repair Service Center</font>", normal),
            Paragraph("<b>INVOICE</b>", h),
        ]],
        colWidths=[3.6 * inch, 3.0 * inch],
    )
    header.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("ALIGN", (1, 0), (1, 0), "RIGHT")]))
    story += [header, Spacer(1, 6)]

    # Meta block
    meta = Table(
        [
            [Paragraph("<b>Bill to</b>", small), Paragraph("<b>Invoice #</b>", small), Paragraph(invoice.number, normal)],
            [Paragraph(customer.name, normal), Paragraph("<b>Issued</b>", small), Paragraph(invoice.issued_at.strftime("%b %d, %Y"), normal)],
            [Paragraph(customer.billing_address or "", small), Paragraph("<b>Due</b>", small),
             Paragraph(invoice.due_date.strftime("%b %d, %Y") if invoice.due_date else "On receipt", normal)],
            [Paragraph(f"Account {customer.account_number}", small), Paragraph("<b>Work order</b>", small), Paragraph(work_order.number, normal)],
        ],
        colWidths=[3.6 * inch, 1.2 * inch, 1.8 * inch],
    )
    meta.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("TOPPADDING", (0, 0), (-1, -1), 1), ("BOTTOMPADDING", (0, 0), (-1, -1), 1)]))
    story += [meta, Spacer(1, 10)]

    # Equipment line
    if equipment:
        eq = f"{equipment.equipment_type.value.title()} — {equipment.manufacturer or ''} {equipment.model or ''} · S/N {equipment.serial_number or 'n/a'}"
        story += [Paragraph(f"<b>Equipment serviced:</b> {eq}", small),
                  Paragraph(f"<b>Repair:</b> {work_order.title}", small), Spacer(1, 10)]

    # Line items
    rows = [["Description", "Type", "Qty", "Unit", "Amount"]]
    for ln in invoice.lines:
        rows.append([ln.description, ln.kind.title(), f"{ln.quantity:g}", _money(ln.unit_price), _money(ln.line_total)])
    tbl = Table(rows, colWidths=[3.2 * inch, 0.9 * inch, 0.6 * inch, 0.9 * inch, 1.0 * inch])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
        ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story += [tbl, Spacer(1, 8)]

    # Totals
    totals = Table(
        [["Subtotal", _money(invoice.subtotal)], ["Tax", _money(invoice.tax)], ["Total Due", _money(invoice.total)]],
        colWidths=[1.4 * inch, 1.2 * inch], hAlign="RIGHT",
    )
    totals.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "RIGHT"), ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("LINEABOVE", (0, 2), (-1, 2), 1, BRAND), ("FONTNAME", (0, 2), (-1, 2), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 2), (-1, 2), ACCENT), ("TOPPADDING", (0, 2), (-1, 2), 6),
    ]))
    story += [totals, Spacer(1, 18)]

    status = "PAID" if invoice.status.value == "paid" else "PAYMENT DUE"
    story += [Paragraph(f"<b>Status:</b> {status}", normal)]
    if invoice.notes:
        story += [Spacer(1, 6), Paragraph(invoice.notes, small)]
    story += [Spacer(1, 24), Paragraph("Thank you for your business. Generated by Serviceflow.", small)]

    doc.build(story)
    return buf.getvalue()
