"""v3: locations + location_id on work orders and equipment

Revision ID: 2dca9a9e290a
Revises: de309371a2da
Create Date: 2026-07-29 14:08:08.222605
"""
from alembic import op
import sqlalchemy as sa


revision = '2dca9a9e290a'
down_revision = 'de309371a2da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_location_org_code')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_location_id'), ['location_id'], unique=False)
        batch_op.create_foreign_key('fk_equipment_location', 'locations', ['location_id'], ['id'])

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_orders_location_id'), ['location_id'], unique=False)
        batch_op.create_foreign_key('fk_work_orders_location', 'locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_orders_location', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_work_orders_location_id'))
        batch_op.drop_column('location_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_location', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_equipment_location_id'))
        batch_op.drop_column('location_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_organization_id'))

    op.drop_table('locations')
    # ### end Alembic commands ###
