"""v5: equipment spec field templates

Revision ID: b7d35e23594d
Revises: 0a10a5861df9
Create Date: 2026-08-04 21:30:06.920192
"""
from alembic import op
import sqlalchemy as sa


revision = 'b7d35e23594d'
down_revision = '0a10a5861df9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_spec_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_spec_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_spec_fields_equipment_type'), ['equipment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_spec_fields_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_spec_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_spec_fields_organization_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_spec_fields_equipment_type'))

    op.drop_table('equipment_spec_fields')
    # ### end Alembic commands ###
